### ISSUE TITLE
Error getting while using  wstool for hratc2015 framework

### ISSUE THREAD

**Issue by qboticslabs** [ras-sight/hratc2015_framework#6]
ERROR in config: Invalid multiproject yaml format in [https://raw.github.com/ras-sight/hratc2015_framework/master/hratc2015_framework.rosinstall]: mapping values are not allowed here
  in "<file>", line 29, column 15

We identified that , there is space b/w uri and link in hratc2015_framework.rosinstall 

- git:
    uri:https://github.com/brNX/robot_self_filter.git
    local-name: robot_self_filter
    version: master

we have to correct it by leaving a space here 

- git:
    uri: https://github.com/brNX/robot_self_filter.git
    local-name: robot_self_filter
    version: master

It has no space. It would be great if you solve this issue.. 

Thanks
Team Zephyr

**Comment by goncabrita** [comment]
Thanks for the heads up Team Zephyr!
